version: '3'
services:
  mlflow:
    image: mlflow-server
    ports:
      - "5000:5000"
    networks:
      - mlflow-network
  reagentai:
    image: reagentai
    ports:
      - "7860:7860"
    env_file:
      - .env
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    networks:
      - mlflow-network
networks:
  mlflow-network:
